### ISSUE TITLE
Proxy related errors when previewing non-CORS enabled Feature Layers.

### ISSUE THREAD

**Issue by gbochenek** [Esri/map-and-app-gallery-template#215] opened 2017-04-05 16:30 UTC
To recreate this issue:
1. Add a new feature layer (non-CORS enabled) to your group.
2. Preview the feature layer from within the Map and App Gallery Template

The application will fail to load and throw an error relating to an unknown proxy url.

This issue is two fold:

1. If a hosted or portal environment, the application should automatically populate the proxy url config.
2. If the proxy URL is configured (hosted or not), the application should set the JSAPI default appropriately.

Pull request incoming...

**Comment by MikeTschudi** [comment] 2017-04-06 15:54
@gbochenek, thanks for the improvement. I merged it into branch [improve-hosted-proxy-handling](https://github.com/Esri/map-and-app-gallery-template/tree/improve-hosted-proxy-handling) via a cherry pick so that it would apply to the develop branch and added a call to `urlUtils.addProxyRule` for the proxyUrl that you created for hosted apps.

@allisonmuise, fyi

**Comment by allisonmuise** [comment] 2017-04-06 15:56
@MikeTschudi Should this be released with 5.2?

**Comment by MikeTschudi** [comment] 2017-04-06 16:00
@allisonmuise, yes, please--I think that it's an important fix

**Comment by allisonmuise** [comment] 2017-04-25 17:20
@MikeTschudi : MAG has been broken on devext since this was installed. Could you please investigate? 

cc @skrishn

**Comment by MikeTschudi** [comment] 2017-04-25 18:27
@allisonmuise, @skrishn, what are you seeing?

I just brought up MAG and it failed with an `SyntaxError: Unexpected token <`. It was caused by the app querying for a group and the server returning HTML instead of JSON, e.g., `http://org.arcgis.com/sharing/rest/community/groups?q=groupid?f=json&token=123` and getting this page: http://nw-brews.mapsdevext.arcgis.com/sharing/rest/community/groups.

The cause appears to be a fault in the URL: the query and format parameters are separated by `?` instead of `&`. This appears to be caused by how the JSAPI `esri/request` call builds the URL, and that's where I'm digging now.

If you are seeing something different, please add it to this issue.

**Comment by MikeTschudi** [comment] 2017-04-25 21:35
`esri/request` has a `content` parameter for query parameters; it does not support query parameters in the `url` parameter. From an example in the [documentation](https://developers.arcgis.com/javascript/3/jsapi/esri.request-amd.html):
```
  var layersRequest = esriRequest({
    url: layerUrl,
    content: { f: "json" },
    handleAs: "json",
    callbackParamName: "callback"
  });
```

Because `esri/request` simply appends "?" and query parameters from the `content` parameter to the URL, we end up with a malformed URLs if the `url` parameter has a query parameter. E.g., if `url` is `http://server/item?q=abc&s=def`, in the above example, we'd get `http://server/item?q=abc&s=def?f=json`

While the `esri/request` documentation does not say that the URL has to be free of query parameters, it does provide a way to handle them via the `content` parameter, so the app's erroneous URLs should be fixed in the app rather than in the JSAPI. Fortunately, most servers have been forgiving of the malformed URLs; this issue happened to have flushed it out.

map-and-app-gallery-template has several places where a query parameter or two is added to the URL:

itemDetails.js:
```
groupUrl = dojo.configData.values.portalURL + "/sharing/rest/community/groups?q=title:\"" + dojo.configData.values.basemapGroupTitle + "\" AND owner:" + dojo.configData.values.basemapGroupOwner + "&f=json";
groupRequest = esriRequest({
    url: groupUrl,
    callbackParamName: "callback"
});
```
```
var groupUrl = dojo.configData.values.portalURL + "/sharing/rest/community/groups?q=" + dojo.BaseMapGroupQuery + "&f=json" + tokenString;
this.searchPortalURL = dojo.configData.values.portalURL;
this._fetchBaseMapLayers(groupUrl, basemapDeferred);
    :    :    :
_fetchBaseMapLayers: function (groupUrl, basemapDeferred) {
    var groupRequest;
    groupRequest = esriRequest({
        url: groupUrl,
        callbackParamName: "callback"
    });
```
```
searchUrl = this.searchPortalURL + '/sharing/rest/search?q=group:' + groupInfo.results[0].id + "&sortField=name&sortOrder=desc&num=50&f=json";
webmapRequest = esriRequest({
    url: searchUrl,
    callbackParamName: "callback"
});
```
```
url1 = data.url + "?f=json";
esriRequest({
    url: url1,
    handleAs: "json",
    load: function (jsondata) {
        if (jsondata.layers.length > 0) {
            _self.addLayerToMap(mapId, data.url, data.title, dataType, jsondata.layers);
        }
    },
```
```
esriRequest({
    url: url + "?f=json",
    load: lang.hitch(this, function (data) {
        var lyr;

        for (p = 0; p < data.layers.length; p++) {
            lyr = url + data.layers[p].id;
            this._addFeaturelayerToMap(map, data.layers[p].name, lyr, data.layers[p].name, layerInfo, false);
        }
        this.createLegend(layerInfo, map, this.legendDiv);
        this._setExtentForLayer(map, url, true);
    }),
    error: function (err) {
        alert(err.message);
    }
});
```
```
var _self = this, url1 = url + "?f=json";
esriRequest({
    url: url1,
    load: function (data) {
        var geometryService, layerExtent;
```

itemDetailsHelper.js:
```
esriRequest({
    url: dojo.locatorURL + '/suggest?text=' + this.txtAddressSearch.value + '&location=' + dojo.toJson(this.location),
    content: {
        'f': 'json'
    },
```
```
if (dojo.enableGeocodeSuggest) {
    queryURL = dojo.locatorURL + '/find?text=' + this.txtAddressSearch.value + '&location=' + dojo.toJson(this.location) + '&magicKey=' + candidateMagicKey;
} else {
    queryURL = dojo.locatorURL + '/find?text=' + this.txtAddressSearch.value + '&location=' + dojo.toJson(this.location);
}
esriRequest({
    url: queryURL,
    content: {
        'f': 'json',
        'outSR': this.map.spatialReference.wkid
    },
```

searchAGOLGroupItems.js:
```
esriRequest({
    // group rest URL
    url: dojo.configData.values.portalURL + '/sharing/rest/community/groups?q=' + dojo.configData.values.group,
    content: {
        'f': 'json'
    },
```

The following routine in searchAGOLGroupItems.js will take more work because it is the recipient of a publish event from four locations. Each publisher and the function will have to separate the URL from the query parameters.
```
queryItemInfo: function (itemUrl, defObj) {
    esriRequest({
        url: itemUrl,
        callbackParamName: "callback",
```

**Comment by allisonmuise** [comment] 2017-04-26 14:55
@MikeTschudi  @skrishn : MAG is workign this morning with these changes backed out.

**Comment by MikeTschudi** [comment] 2017-04-26 15:11
It appears that esri/request behaves differently if the request is going through a proxy than if it is not.

With a proxy (probably the use of esriConfig.defaults.io.proxyUrl), the query parameters in the content property are appended without checking the URL for existing query parameters.

Without a proxy, the query parameters are appended after adjusting for the presence of “?” in the URL.

**Comment by allisonmuise** [comment] 2018-03-21 16:29
closing - app will be moved to mature support at 6.1. Use Minimal Gallery app instead.

**Closed by allisonmuise** 2018-03-21 16:29 UTC
Labels: bug, wontfix
